### ISSUE TITLE
Add support for ESX Weight 

### ISSUE THREAD

**Issue by vichuvrn** [ESX-PUBLIC/esx_diving#2]

**Comment by rex2630** [comment]
https://github.com/ESX-PUBLIC/esx_diving/commit/543f204809ac7e1510e9405cf6097f9f71017510 This should  be it. Tell me if its all good :)

**Comment by vichuvrn** [comment]
great.. i was confused of -1 
is their any equivalent of -1 in new weight system ?

**Comment by rex2630** [comment]
No, i dont think so

**Comment by vichuvrn** [comment]
@rex2630  okay thanks.. can you do me a favor .. can you please delete this issue

**Comment by rex2630** [comment]
I cant delete it, leave it closed. Its almost the same

**Comment by vichuvrn** [comment]
@ElPumpo can you do me a favor .. can you please delete this issue

**Comment by rex2630** [comment]
He do have same permissions as me. Nobody can delete this man...

**Comment by vichuvrn** [comment]
@rex2630  okay .. thank you..
